from App.tests.test_base import *
from App.tests.test_competition import *
from App.tests.test_integration import *
from App.tests.test_moderator import *
from App.tests.test_notification import *
from App.tests.test_ranking_history import *
from App.tests.test_team import *
from App.tests.test_student import *
from App.tests.test_user import *
